baseURL = 'https://adelinewei.github.io/'
languageCode = 'en-us'
title = 'The Fun Corner'
theme = "loveit"

[params]
    # LoveIt theme version
    version = "0.2.X"
	defaultTheme = "light"

    [params.home]
        [params.home.profile]
            subtitle = ""   # TODO: add some words for this website
            typeit = false
    [params.header]
        mobileMode = "auto"
        [params.header.title]
            name = "The Fun Corner"
	[params.footer]
		since = 2022

	[params.page]
		[params.page.share]
			enable = true
			Linkedin = true
			Twitter = false
			Facebook = false
			HackerNews = false
			Weibo = false
		[params.page.comment]
			[params.page.comment.valine]
				enable = true
				appId = "VALINE_APP_ID"
				appKey = "VALINE_APP_KEY"
				placeholder = ""
				avatar = "mp"
				meta= ""
				pageSize = 10

[menu]
    [[menu.main]]
		identifier = "posts"
		pre = ""
		post = ""
		name = "Posts"
		url = "/posts/"
		titel = ""
		weight = 1

	[[menu.main]]
		identifier = "tags"
		pre = ""
		post = ""
		name = "Tags"
		url = "/tags/"
		title = ""
		weight = 2

	[[menu.main]]
		identifier = "about"
		pre = ""
		post = ""
		name = "About"
		url = "/about/"
		title = ""
		weight = 3

	[[menu.main]]
		identifier = "github"
		pre = "<i class='fa-brands fa-github fa-lg' aria-hidden='true'></i>"
		post = ""
		name = ""
		url = "https://github.com/adelinewei"
		title = ""
		weight = 4
