name: GitHub Pages

on:
  push:
    branches:
      - main  # Set a branch to deploy
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-22.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.102.3'
          extended: true

      - name: Prepare Environment Secrets
        run: |
          sed -i 's/VALINE_APP_ID/${{ secrets.VALINE_APP_ID }}/' config.toml
          sed -i 's/VALINE_APP_KEY/${{ secrets.VALINE_APP_KEY }}/' config.toml
          sed -i 's/ALGOLIA_APP_ID/${{ secrets.ALGOLIA_APP_ID }}/' config.toml
          sed -i 's/ALGOLIA_SEARCH_KEY/${{ secrets.ALGOLIA_SEARCH_KEY }}/' config.toml
        env:
          VALINE_APP_ID: ${{ secrets.VALINE_APP_ID }}
          VALINE_APP_KEY: ${{ secrets.VALINE_APP_KEY }}
          ALGOLIA_APP_ID: ${{ secrets.ALGOLIA_APP_ID }}
          ALGOLIA_SEARCH_KEY: ${{ secrets.ALGOLIA_SEARCH_KEY }}

      - name: Build
        run: hugo --minify -e production

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public